# This is a configuration script for travis-ci.com, that specifies actions to
# be taken whenever a commit is pushed to github. For this to work, you need
# a travis-ci account:
language: python
python:
  - "3.7"
  - "3.8"

install:
  # Need recent pip versions to deal with the most recent manylinux wheels:
  - pip install --upgrade pip
  - pip install -e .

  # Further tools for packaging/testing:
  - pip install wheel twine flake8 pytest coverage coveralls

script:
  # Check wheel/source distribution for obvious problems
  # (missing version, invalid markdown in README, etc):
  - python setup.py sdist bdist_wheel
  - twine check dist/*

  # Static analysis (style checks, missing imports, typos, code complexity):
  - flake8

  # Project specific tests:
  - coverage run --source=src -m pytest tests

after_success:
  # Upload coverage results to coveralls.io:
  # (for this to work, you need an account there)
  - coverage combine
  - coveralls
